In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("dataset.csv", nrows=5000)

In [3]:
df.head()

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,Star3,Star4,Writer,Director_of_Photography,Producers,Music_Composer,genres_list,Cast_list,overview_sentiment,all_combined_keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Elliot Page,Ken Watanabe,Christopher Nolan,Wally Pfister,"Thomas Tull, Christopher Nolan, Chris Brigham,...",Hans Zimmer,"['Action', 'Science Fiction', 'Adventure']","['Tim Kelleher', 'Silvie Laguna', 'Natasha Bea...",-0.011111,"['s', 'philosophy', 'skilled', 'kidnapping', '..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Jessica Chastain,Mackenzie Foy,Jonathan Nolan,Hoyte van Hoytema,"Jake Myers, Emma Thomas, Jordan Goldberg, Thom...",Hans Zimmer,"['Adventure', 'Drama', 'Science Fiction']","['Jeff Hephner', 'William Devane', 'Elyes Gabe...",0.045455,"['thoughtful', 'use', 'scientist', 'quantum me..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,Aaron Eckhart,Michael Caine,Jonathan Nolan,Wally Pfister,"Kevin De La Noy, Thomas Tull, Christopher Nola...","Hans Zimmer, James Newton Howard","['Drama', 'Action', 'Crime', 'Thriller']","['Tommy Lister Jr.', 'Edison Chen', 'Beatrice ...",0.025000,"['reign', 'harvey', 'proves', 'partnership', '..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Sigourney Weaver,Michelle Rodriguez,James Cameron,Mauro Fiore,"Jon Landau, Colin Wilson, Laeta Kalogridis, Ja...",James Horner,"['Action', 'Adventure', 'Fantasy', 'Science Fi...","['Carvon Futrell', 'Joel David Moore', 'Jon Cu...",0.041667,"['space war', 'civilization', 'society', 'mari..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,Scarlett Johansson,Jeremy Renner,Sydney Newman,NaN,NaN,NaN,"['Science Fiction', 'Action', 'Adventure']","['Haneyuri', 'Nako Mizusawa', 'Marin', 'Rikako...",0.025000,"['s', 'world', 'begins', 'e', 'global safety',..."

In [4]:
df.columns

Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'adult', 'backdrop_path', 'budget', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'tagline', 'production_companies',
       'production_countries', 'spoken_languages', 'keywords', 'release_year',
       'Director', 'AverageRating', 'Poster_Link', 'Certificate',
       'IMDB_Rating', 'Meta_score', 'Star1', 'Star2', 'Star3', 'Star4',
       'Writer', 'Director_of_Photography', 'Producers', 'Music_Composer',
       'genres_list', 'Cast_list', 'overview_sentiment',
       'all_combined_keywords'],
      dtype='object')

In [5]:
needed_cols = [
    'id', 'title', 'overview', 'genres_list', 'all_combined_keywords',
    'release_year', 'Director', 'Cast_list'
]

df = df[needed_cols]
df = df.drop_duplicates(subset=['title'])

In [6]:
df.head()

,id,title,overview,genres_list,all_combined_keywords,release_year,Director,Cast_list
0,27205,Inception,"Cobb, a skilled thief who commits corporate es...","['Action', 'Science Fiction', 'Adventure']","['s', 'philosophy', 'skilled', 'kidnapping', '...",2010.0,Christopher Nolan,"['Tim Kelleher', 'Silvie Laguna', 'Natasha Bea..."
1,157336,Interstellar,The adventures of a group of explorers who mak...,"['Adventure', 'Drama', 'Science Fiction']","['thoughtful', 'use', 'scientist', 'quantum me...",2014.0,Christopher Nolan,"['Jeff Hephner', 'William Devane', 'Elyes Gabe..."
2,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,"['Drama', 'Action', 'Crime', 'Thriller']","['reign', 'harvey', 'proves', 'partnership', '...",2008.0,Christopher Nolan,"['Tommy Lister Jr.', 'Edison Chen', 'Beatrice ..."
3,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","['Action', 'Adventure', 'Fantasy', 'Science Fi...","['space war', 'civilization', 'society', 'mari...",2009.0,James Cameron,"['Carvon Futrell', 'Joel David Moore', 'Jon Cu..."
4,24428,The Avengers,When an unexpected enemy emerges and threatens...,"['Science Fiction', 'Action', 'Adventure']","['s', 'world', 'begins', 'e', 'global safety',...",2012.0,Joss Whedon,"['Haneyuri', 'Nako Mizusawa', 'Marin', 'Rikako..."

In [7]:
df.rename(columns={
    'overview': 'description',
    'genres_list': 'genres',
    'all_combined_keywords': 'tags',
    'Director': 'director',
    'Cast_list': 'actors'
}, inplace=True)

In [8]:
df['description'] = df['description'].fillna("")
df['director'] = df['director'].fillna("")

In [9]:
df.to_csv("processed_movies.csv", index=False)

In [10]:
pd.read_csv("processed_movies.csv")

,id,title,description,genres,tags,release_year,director,actors
0,27205,Inception,"Cobb, a skilled thief who commits corporate es...","['Action', 'Science Fiction', 'Adventure']","['s', 'philosophy', 'skilled', 'kidnapping', '...",2010.0,Christopher Nolan,"['Tim Kelleher', 'Silvie Laguna', 'Natasha Bea..."
1,157336,Interstellar,The adventures of a group of explorers who mak...,"['Adventure', 'Drama', 'Science Fiction']","['thoughtful', 'use', 'scientist', 'quantum me...",2014.0,Christopher Nolan,"['Jeff Hephner', 'William Devane', 'Elyes Gabe..."
2,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,"['Drama', 'Action', 'Crime', 'Thriller']","['reign', 'harvey', 'proves', 'partnership', '...",2008.0,Christopher Nolan,"['Tommy Lister Jr.', 'Edison Chen', 'Beatrice ..."
3,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","['Action', 'Adventure', 'Fantasy', 'Science Fi...","['space war', 'civilization', 'society', 'mari...",2009.0,James Cameron,"['Carvon Futrell', 'Joel David Moore', 'Jon Cu..."
4,24428,The Avengers,When an unexpected enemy emerges and threatens...,"['Science Fiction', 'Action', 'Adventure']","['s', 'world', 'begins', 'e', 'global safety',...",2012.0,Joss Whedon,"['Haneyuri', 'Nako Mizusawa', 'Marin', 'Rikako..."
...,...,...,...,...,...,...,...,...
995,4248,Scary Movie 2,While the original parodied slasher flicks lik...,['Comedy'],"['s', 'keenen', 'hell', 'visit', 'jinks ensue'...",2001.0,Michael Bay,['Unknown']
996,7980,The Lovely Bones,"After being brutally murdered, 14-year-old Sus...","['Fantasy', 'Drama']","['watches', 'revenge', 'balance', 'lives', 'st...",2009.0,Robert Eggers,"['Arswendi Nasution', 'Noordin Gade', 'Nungki ..."
997,9023,Spirit: Stallion of the Cimarron,As a wild stallion travels across the frontier...,"['Animation', 'Adventure', 'Comedy', 'Family',...","['west', 'true', 'pets', 'stallion', 'travels'...",2002.0,John Lee Hancock,['Unknown']
998,1878,Fear and Loathing in Las Vegas,Raoul Duke and his attorney Dr. Gonzo drive a ...,"['Adventure', 'Drama', 'Comedy']","['dr', 'begins', 'stoned', 'paranoia', 'mojave...",1998.0,Terry Gilliam,['Shaun McManus']
999,9802,The Rock,When vengeful General Francis X. Hummel seizes...,"['Action', 'Adventure', 'Thriller']","['x', 'island prison', 'control', 'penetrate',...",1996.0,John Carpenter,['Unknown']